config/routes.rb
PasswordApp::Application.routes.draw do

  resources :items

  resources :folders

  resources :users

  resources :groups

  controller :sessions do
    get "login" => :new
    post "login" => :create
    delete "logout" => :destroy
  end

  controller :favorites do
    get "favorites" => :index
    post "favorites" => :create
    delete "favorites" => :destroy
  end

  controller :help do
    get "help" => :index
  end

  root :to => "favorites#index"
end

app/models/folder.rb
class Folder < ActiveRecord::Base
  default_scope where(:deleted => false)

  has_many :groupings, :dependent => :destroy
  has_many :groups, :through => :groupings
  has_many :items, :dependent => :destroy
  has_many :belongings, :dependent => :destroy
  has_many :users, :through => :belongings
  validates :name, :presence => true, :uniqueness => true
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  skip_before_filter :require_session
  before_filter :require_login
  before_filter :exclude_employees, :only => [:new, :edit, :destroy]
  def require_login
    unless session[:user_id]
      redirect_to(login_url)
    end
  end

  def index
    @folders = User.find(session[:user_id]).get_folders
    unless @folders
      @folders = []
    end
  end

  def show
    @folder = User.find(session[:user_id]).get_folder(params[:id])
    unless @folder
      redirect_to(:action => "index")
    end
  end

  def new
    @folder = Folder.new
  end

  def edit
    @folder = Folder.find(params[:id])
  end

  def create
    @folder = Folder.new(params[:folder])

    if @folder.save
      redirect_to folders_url
    else
      render :action => "new"
    end
  end

  def update
    params[:folder][:group_ids] ||= []
    params[:folder][:user_ids] ||= []
    @folder = Folder.find(params[:id])

    if @folder.update_attributes(params[:folder])
      redirect_to folders_url
    else
      render :action => "edit"
    end
  end

  def destroy
    @folder = Folder.find(params[:id])
    @folder.deleted = true

    if @folder.save
      redirect_to(folders_url)
    end
  end
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/views/folders/_form.html.haml
:javascript
  jQuery(document).ready(function() {
    jQuery("#tree").checkboxTree({
      collapsedarrow: "/images/checkboxtree/img-arrow-collapsed.gif",
      expandedarrow: "/images/checkboxtree/img-arrow-expanded.gif",
      blankarrow: "/images/checkboxtree/img-arrow-blank.gif",
      checkchildren: false,
      checkparents: false
    });
  });

= form_for @folder, :validate => true do |f|
  .field
    = f.label :name, "フォルダ名"
    .input
      = f.text_field :name
  .field
    = f.label :group, "グループ(ユーザー)"
    .input
      %ul#tree.unorderedlisttree
        - Group.all.each do |group|
          %li
            = check_box_tag "folder[group_ids][]", group.id, group.folders.include?(@folder)
            %label= group.name
            %ul
              - group.users.each do |user|
                %li
                  = check_box_tag "folder[user_ids][]", user.id, user.folders.include?(@folder)
                  %label= user.name
  .actions
    = f.submit '保存'

app/views/folders/_items_list.html.haml
:javascript
  $(document).ready(function() {
    $("#example").dataTable({
      "bJQueryUI":true,
      "sPaginationType":"full_numbers",
      "bStateSave": true
    })
  });

%div#demo
  %table#example.display{:cellpadding => "0", :cellspacing => "0", :border => "0"}
    %thead
      %tr
        %th アイテム名
        %th アカウント
        %th パスワード
        %th URL
        %th
        %th
        %th
    %tbody
      - items.each do |item|
        %tr
          %td= item.name
          %td= item.account
          %td= item.decrypt_password
          %td= item.url
          %td.center= link_to image_tag('/images/like.png'), favorites_url(:item_id => item), :method => :post, :title => "お気に入りに追加する"
          %td.center= link_to image_tag('/images/edit.png'), edit_item_path(item), :title => "編集"
          %td.center= link_to image_tag('/images/del.png'), item, :confirm => 'Are you sure?', :method => :delete, :title => "削除"

%br

app/views/folders/_new_item.html.haml
%h3
  %span アイテムを追加する

= form_for item, :validate => true do |f|
  .field
    = f.hidden_field :folder_id
  .field
    = f.label :name, "アイテム名"
    .input
      = f.text_field :name
  .field
    = f.label :account, "アカウント"
    .input
      = f.text_field :account
  .field
    = f.label :password, "パスワード"
    .input
      = f.text_field :password
  .field
    = f.label :url, "URL"
    .input
      = f.text_area :url, :rows => 3
  .actions
    = f.submit '保存'

app/views/folders/edit.html.haml
%h2
  %span フォルダ編集

%div.innerContent
  = render 'form'

app/views/folders/index.html.haml
:javascript
  $(document).ready(function() {
    $("#jstable").dataTable({
      "bJQueryUI":true,
      "sPaginationType":"full_numbers",
      "bStateSave": true
    });
    $("#tabs").tabs({
      cookie:{
        expires: 7
      }
    });
  });

%h2
  %span フォルダ

%div.innerContent
  %div#tabs
    %ul
      %li
        %a{:href => "#folderList", :title => "アイコン表示"}
          %img{:src => "/images/grid.png"}
      %li
        %a{:href => "#dtTable", :title => "リスト表示"}
          %img{:src => "/images/list.png"}

    %div#dtTable
      %table#jstable.display{:cellpadding => "0", :cellspacing => "0", :border => "0"}
        %thead
          %tr
            %th フォルダ名
            %th アイテム数
            %th グループ
            %th 個別ユーザー
            %th
            %th
        %tbody
          - @folders.each do |folder|
            %tr
              %td= link_to folder.name, folder
              %td.center= folder.items.count
              %td
                - folder.groups.each do |group|
                  = link_to group.name, group
              %td
                - folder.users.each do |user|
                  = user.name
              - if current_user.role < 2
                %td.center= link_to image_tag('/images/edit_folder.png'), edit_folder_path(folder)
                %td.center= link_to image_tag('/images/del_folder.png'), folder, :confirm => "Are you sure?", :method => :delete
              - else
                %td.center
                  ー
                %td.center
                  ー
      %br
    %div#folderList
      - @folders.each do |folder|
        %div.fBlock
          %span.folder= link_to folder.name, folder
          %div.itemCnt
            = link_to image_tag('/images/nav_item.png', :width => "12", :height => "12"), folder
            %span.num= folder.items.count
          %div.btnList
            - if current_user.role < 2
              = link_to image_tag('/images/edit_folder.png', :width => "12", :height => "12"), edit_folder_path(folder)
              = link_to image_tag('/images/del_folder.png', :width => "12", :height => "12"), folder, :confirm => "Are you sure?", :method => :delete

      %div.clear

- if current_user.role < 2
  = link_to image_tag('/images/add_folder.png'), new_folder_path, {:title => "新規作成"}

app/views/folders/new.html.haml
%h2
  %span 新規フォルダ

%div.innerContent
  = render 'form'

app/views/folders/show.html.haml
%h2
  %span= @folder.name

%div.innerContent

  = render "items_list", {:items => @folder.items}
  = render "new_item", {:item => @folder.items.new}

  = link_to image_tag('/images/back.png'), folders_path, {:title => "一覧に戻る"}