config/routes.rb
PasswordApp::Application.routes.draw do

  resources :items

  resources :folders

  resources :users

  resources :groups

  controller :sessions do
    get "login" => :new
    post "login" => :create
    delete "logout" => :destroy
  end

  controller :favorites do
    get "favorites" => :index
    post "favorites" => :create
    delete "favorites" => :destroy
  end

  controller :help do
    get "help" => :index
  end

  root :to => "favorites#index"
end

app/models/group.rb
class Group < ActiveRecord::Base
  default_scope where(:deleted => false)

  has_many :memberships, :dependent => :destroy
  has_many :users, :through => :memberships
  has_many :groupings, :dependent => :destroy
  has_many :folders, :through => :groupings

  validates :name, :presence => true, :uniqueness => true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :admin_only, :except => [:index, :show]

  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end

  def edit
    @group = Group.find(params[:id])
  end

  def create
    @group = Group.new(params[:group])
    if @group.save
      redirect_to :action => "index"
    else
      render :action => "new"
    end
  end

  def update
    params[:group][:user_ids] ||= []
    @group = Group.find(params[:id])
    if @group.update_attributes(params[:group])
      redirect_to :action => "index"
    else
      render :action => "edit"
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.deleted = true

    if @group.save
      redirect_to(groups_url)
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.haml
= form_for @group, :validate => true, :html => {:class => "jqtransform"} do |f|
  .field
    = f.label :name, "グループ名"
    .input
      = f.text_field :name
  .field
    = f.label :user, "ユーザー"
    .input
      - User.all.each do |user|
        = check_box_tag "group[user_ids][]", user.id, user.groups.include?(@group)
        = user.name
  .actions
    = f.submit '保存'

app/views/groups/edit.html.haml
%h2
  %span グループ編集

%div.innerContent
  = render 'form'

app/views/groups/index.html.haml
:javascript
  $(document).ready(function() {
    $("#jstable").dataTable({
      "bJQueryUI":true,
      "sPaginationType":"full_numbers",
      "bStateSave": true
    });
  });

%h2
  %span グループ

%div.innerContent
  %table#jstable.display{:cellpadding => "0", :cellspacing => "0", :border => "0"}
    %thead
      %tr
        %th グループ名
        %th ユーザー数
        %th
        %th
    %tbody
      - @groups.each do |group|
        %tr
          %td= link_to group.name, group
          %td.center= group.users.size
          - if current_user.role == 0
            %td.center= link_to image_tag('/images/edit_group.png', :align => "center"), edit_group_path(group), :title => "編集"
            %td.center= link_to image_tag('/images/del_group.png', :align => "center"), group, :confirm => 'Are you sure?', :method => :delete, :title => "削除"
          - else
            %td.center
              ー
            %td.center
              ー

%br

- if current_user.role == 0
  = link_to image_tag('/images/add_group.png'), new_group_path, {:title => "新規作成"}

app/views/groups/new.html.haml
%h2
  %span 新規グループ

%div.innerContent
  = render 'form'

app/views/groups/show.html.haml
%h2
  %span= @group.name

%div.innerContent
  %ul#userList
    - @group.users.each do |user|
      - if current_user.role == 0
        %li= link_to user.name, edit_user_path(user)
      - else
        %li= user.name
  %br
  = link_to image_tag('/images/back.png'), groups_url, {:title => "一覧に戻る"}