config/routes.rb
PasswordApp::Application.routes.draw do

  resources :items

  resources :folders

  resources :users

  resources :groups

  controller :sessions do
    get "login" => :new
    post "login" => :create
    delete "logout" => :destroy
  end

  controller :favorites do
    get "favorites" => :index
    post "favorites" => :create
    delete "favorites" => :destroy
  end

  controller :help do
    get "help" => :index
  end

  root :to => "favorites#index"
end

app/models/item.rb
require 'crypt_util'
class Item < ActiveRecord::Base
  default_scope where(:deleted => false)

  has_many :favorites
  has_many :users, :through => :favorites
  has_one :sugar, :dependent => :destroy
  belongs_to :folder

  validates_presence_of :name, :folder_id

  attr_accessor :password
  validates :password, :presence => true, :on => :create

  before_save :encrypt_password
  after_create :create_sugar

  def encrypt_password
    if password.present?
      @salt = CryptUtil.create_password
      self.encrypted_password = CryptUtil.encrypt(password, ATOMIC, @salt)
    end
  end

  def decrypt_password
    sugar = Sugar.find_by_item_id(id)
    CryptUtil.decrypt(self.encrypted_password, ATOMIC, sugar.salt)
  end

  def create_sugar
    Sugar.create!(:item_id => id, :salt => @salt)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = User.find(session[:user_id]).get_items
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def edit
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(params[:item])

    if @item.save
      redirect_to(@item.folder, :notice => 'Item was successfully created.')
    else
      render :action => "new"
    end
  end

  def update
    @item = Item.find(params[:id])

    if @item.update_attributes(params[:item])
      redirect_to(@item.folder, :notice => 'Item was successfully updated.')
    else
      render :action => "edit"
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.deleted = true

    if @item.save
      redirect_to(items_url)
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.haml
= form_for @item, :validate => true do |f|
  .field
    = f.label :folder, "フォルダ"
    .input
      = f.select "folder_id", Folder.all.collect {|f| [f.name, f.id]}, {:include_blank => true}
  .field
    = f.label :name, "アイテム名"
    .input
      = f.text_field :name
  .field
    = f.label :account, "アカウント"
    .input
      = f.text_field :account
  .field
    = f.label :password, "パスワード"
    .input
      = f.text_field :password
  .field
    = f.label :url, "URL"
    .input
      = f.text_area :url, :rows => 3
  .actions
    = f.submit '保存'

app/views/items/edit.html.haml
%h2
  %span アイテム編集

%div.innerContent
  = render 'form'

app/views/items/index.html.haml
:javascript
  $(document).ready(function() {
    $("#jstable").dataTable({
      "bJQueryUI":true,
      "sPaginationType":"full_numbers",
      "bStateSave": true
    });
  });

%h2
  %span アイテム

%div.innerContent
  %table#jstable.display{:cellpadding => "0", :cellspacing => "0", :border => "0"}
    %thead
      %tr
        %th アイテム名
        %th アカウント
        %th パスワード
        %th URL
        %th フォルダ
        %th
        %th
        %th
    %tbody
      - @items.each do |item|
        %tr
          %td= item.name
          %td= item.account
          %td= item.decrypt_password
          %td= item.url
          %td= link_to item.folder.name, item.folder
          %td.center= link_to image_tag('/images/like.png'), favorites_url(:item_id => item), :method => :post, :title => "お気に入りに追加する"
          %td.center= link_to image_tag('/images/edit.png'), edit_item_path(item), :title => "編集"
          %td.center= link_to image_tag('/images/del_item.png'), item, :confirm => 'Are you sure?', :method => :delete, :title => "削除"

%br

- if current_user.role < 2
  = link_to image_tag('/images/add_item.png'), new_item_path, {:title => "新規作成"}

app/views/items/new.html.haml
%h2
  %span 新規アイテム

%div.innerContent
  = render 'form'

app/views/items/show.html.haml
%p#notice= notice

%p
  %b Folder:
  = @item.folder_id
%p
  %b Name:
  = @item.name
%p
  %b Password:
  = @item.decrypt_password
%p
  %b Account:
  = @item.account
%p
  %b Url:
  = @item.url

= link_to 'Edit', edit_item_path(@item)
\|
= link_to 'Back', items_path